<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add a new address' => '',
    'Add a new prefix' => '',
    'Add new address' => '',
    'Add new aggregate' => '',
    'Add new prefix' => '',
    'Address' => '',
    'Aggregate' => '',
    'Aggregate was created successfully' => '',
    'Aggregate was deleted successfully' => '',
    'Aggregates' => '',
    'An error occurred when trying to add a prefix' => '',
    'An error occurred when trying to add an aggregate' => '',
    'An error occurred when trying to update a prefix' => '',
    'An error occurred when trying to update an aggregate' => '',
    'Child Prefixes' => '',
    'Child prefixes' => '',
    'Description' => '',
    'Description was changed' => '',
    'Edit' => '',
    'Editing IP address {ip}' => '',
    'Examples:' => '',
    'Failed to change description' => '',
    'Family' => '',
    'Format:' => 'Формат:',
    'IP' => '',
    'IP Address' => '',
    'IP Address was created successfully' => '',
    'IP Address was deleted successfully' => '',
    'IP Address was updated successfully' => '',
    'IP Addresses' => '',
    'IP Addresses {count}' => '',
    'IP address was updated successfully' => '',
    'IPAM' => '',
    'IPv4' => '',
    'IPv4 or IPv6 network' => '',
    'IPv4 or IPv6 network with mask' => '',
    'IPv4 or IPv6 network with mask or specify a numeric range to create multiple IPs.' => '',
    'IPv4, IPv6 or IP Range' => '',
    'IPv6' => '',
    'Operational status of this prefix' => '',
    'Parent Prefixes' => '',
    'Parent prefixes' => '',
    'Prefix' => '',
    'Prefix was created successfully' => '',
    'Prefix was deleted successfully' => '',
    'Prefix was updated successfully' => '',
    'Prefixes' => '',
    'RIR' => '',
    'Regional Internet Registry responsible for this prefix' => '',
    'Site' => '',
    'Status' => '',
    'Tags' => '',
    'The primary function of this prefix' => '',
    'Update Prefix' => '',
    'Utilization' => '',
    'VLAN' => '',
    'VLAN group' => '',
    'VRF' => '',
    'Virtual Routing and Forwarding' => '',
    '{v4}, {v6}, {r4}, {r6}' => '',
    'Root prefixes only' => 'Только корневые префиксы'
];
